_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
                - 105
            "3":
                - 2
                - 23
                - 51
                - 55
            "4": 3.9.18
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 1
                - 5
            "9":
                "1": llmapps_generation
            "12": 0.18.6
            "13": linux-x86_64
