_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": usage/total_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": _timestamp
              "6": []
              "7": []
            - "1": usage/completion_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": usage/elapsed_time
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": usage/prompt_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.9.18
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 2
                - 7
                - 23
                - 51
                - 55
            "4": 3.9.18
            "5": 0.18.6
            "8":
                - 1
                - 5
            "9":
                "1": llmapps_generation
            "12": 0.18.6
            "13": linux-x86_64
