_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.5
            "6": 4.37.2
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 20
lr:
    value: 0.005
momentum:
    value: 0.9
norm:
    value: 0.5
